### ISSUE TITLE
Allow include in YAML

### ISSUE THREAD

**Issue by janoszen** [janoszen/cscanner#18]
In order to facilitate reusable configuration files the YAML loader should allow including other YAML files. This will work in both sections as follows

## Connection includes

In the connections section the `include` keyword specifies a file that should be included as connection information:

```yaml
---
connections:
  - include: ./connections.yaml
  - exoscale-test:
      type: exoscale
      key: ""
      secret: ""
rules:
  # Rules go here
```

The file specification can be relative or absolute in path, or may contain a HTTP URL.

### Rules includes

Rule includes work similar to connections:

```yaml
---
connections:
  # Connections go here 
rules:
  - include: ./ssh.yaml
```

The file specification can be relative or absolute in path, or may contain a HTTP URL.

In future there needs to be support for filtering resources before includes too.
