### ISSUE TITLE
Enable specific firewall port

### ISSUE THREAD

**Issue by ecrazor1911** [janoszen/cscanner#21]
Example:

```yaml
connections:
  # Configure your connections here
rules:
  - type: FIREWALL_PUBLIC_SERVICE_ALLOWED
    protocol: "tcp"
    ports:
      - 22
```

New format?

```yaml
connections:
  # Configure your connections here
rules:
  - type: FIREWALL_PUBLIC_SERVICE_ALLOWED
    ports:
      - 22/tcp
      - 53/udp
```

Ref: https://cscanner.io/#cscanner-a-cloud-security-scanner
